=== Alfresco/alfresco-content-app/extension.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "https://github.com/Alfresco/alfresco-content-app/blob/development/extension.schema.json",
    "title": "ACA Extension Schema",
    "description": "Provides a validation schema for ACA extensions",

    "definitions": {
        "ruleRef": {
            "type": "object",
            "required": ["id", "type"],
            "properties": {
                "id": {
                    "description": "Unique rule definition id",
                    "type": "string"
                },
                "type": {
                    "description": "Rule evaluator type",
                    "type": "string"
                },
                "parameters": {
                    "description": "Rule evaluator parameters",
                    "type": "array",
                    "items": { "$ref": "#/definitions/ruleParameter" },
                    "minItems": 1
                }
            }
        },
        "ruleParameter": {
            "type": "object",
            "required": ["type", "value"],
            "properties": {
                "type": {
                    "description": "Rule parameter type",
                    "type": "string"
                },
                "value": {
                    "description": "Rule parameter value",
                    "type": "string"
                },
                "parameters": {
                    "description": "Parameters",
                    "type": "array",
                    "items": { "$ref": "#/definitions/ruleParameter" },
                    "minItems": 1
                }
            }
        },
        "routeRef": {
            "type": "object",
            "required": ["id", "path", "component"],
            "properties": {
                "id": {
                    "description": "Unique route reference identifier.",
                    "type": "string"
                },
                "path": {
                    "description": "Route path to register.",
                    "type": "string"
                },
                "component": {
                    "description": "Unique identifier for the Component to use with the route.",
                    "type": "string"
                },
                "layout": {
                    "description": "Unique identifier for the custom layout component to use.",
                    "type": "string"
                },
                "auth": {
                    "description": "List of the authentication guards to use with the route.",
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "minLength": 1,
                    "uniqueItems": true
                },
                "data": {
                    "description": "Custom data to pass to the activated route so that your components can access it",
                    "type": "object"
                }
            }
        },
        "actionRef": {
            "type": "object",
            "required": ["id", "type"],
            "properties": {
                "id": {
                    "description": "Unique action identifier",
                    "type": "string"
                },
                "type": {
                    "description": "Action type",
                    "type": "string"
                },
                "payload": {
                    "description": "Action payload value (string or expression)",
                    "type": "string"
                }
            }
        },
        "contentActionRef": {
            "type": "object",
            "required": ["id"],
            "properties": {
                "id": {
                    "description": "Unique action identifier.",
                    "type": "string"
                },
                "type": {
                    "description": "Element type",
                    "type": "string",
                    "enum": ["default", "button", "separator", "menu", "custom"]
                },
                "title": {
                    "description": "Element title",
                    "type": "string"
                },
                "description": {
                    "description": "Element description, used for the tooltips.",
                    "type": "string"
                },
                "description-disabled": {
                    "description": "Description to use when element is in the disabled state.",
                    "type": "string"
                },
                "order": {
                    "description": "Element order",
                    "type": "number"
                },
                "icon": {
                    "description": "Element icon",
                    "type": "string"
                },
                "disabled": {
                    "description": "Toggles disabled state",
                    "type": "boolean"
                },
                "component": {
                    "description": "Custom component id (requires type to be 'custom')",
                    "type": "string"
                },
                "children": {
                    "description": "Child entries for the container types.",
                    "type": "array",
                    "items": { "$ref": "#/definitions/contentActionRef" },
                    "minItems": 1
                },
                "actions": {
                    "description": "Element actions",
                    "type": "object",
                    "properties": {
                        "click": {
                            "description": "Action reference for the click handler",
                            "type": "string"
                        }
                    }
                },
                "rules": {
                    "description": "Element rules",
                    "type": "object",
                    "properties": {
                        "enabled": {
                            "description": "Rule to evaluate the enabled state",
                            "type": "string"
                        },
                        "visible": {
                            "description": "Rule to evaluate the visibility state",
                            "type": "string"
                        }
                    }
                }
            }
        },
        "navBarLinkRef": {
            "type": "object",
            "required": ["id", "icon", "title", "route"],
            "properties": {
                "id": {
                    "description": "Unique identifier",
                    "type": "string"
                },
                "icon": {
                    "description": "Element icon",
                    "type": "string"
                },
                "title": {
                    "description": "Element title",
                    "type": "string"
                },
                "route": {
                    "description": "Route reference identifier",
                    "type": "string"
                },
                "description": {
                    "description": "Element description or tooltip",
                    "type": "string"
                },
                "order": {
                    "description": "Element order",
                    "type": "number"
                },
                "disabled": {
                    "description": "Toggles the disabled state",
                    "type": "boolean"
                }
            }
        },
        "navBarGroupRef": {
            "type": "object",
            "required": ["id", "items"],
            "properties": {
                "id": {
                    "description": "Unique identifier for the navigation group",
                    "type": "string"
                },
                "items": {
                    "description": "Navigation group items",
                    "type": "array",
                    "items": { "$ref": "#/definitions/navBarLinkRef" },
                    "minItems": 1
                },
                "order": {
                    "description": "Group order",
                    "type": "number"
                },
                "disabled": {
                    "description": "Toggles the disabled state",
                    "type": "boolean"
                }
            }
        },
        "sidebarTabRef": {
            "type": "object",
            "required": ["id", "component"],
            "properties": {
                "id": {
                    "description": "Unique identifier for the navigation group",
                    "type": "string"
                },
                "title": {
                    "description": "Element title",
                    "type": "string"
                },
                "component": {
                    "description": "Component id",
                    "type": "string"
                },
                "icon": {
                    "description": "Material icon name",
                    "type": "string"
                },
                "disabled": {
                    "description": "Toggles disabled state",
                    "type": "boolean"
                },
                "order": {
                    "description": "Element order",
                    "type": "number"
                },
                "rules": {
                    "description": "Element rules",
                    "type": "object",
                    "properties": {
                        "visible": {
                            "description": "Rule to evaluate the visibility state",
                            "type": "string"
                        }
                    }
                }
            }
        },
        "viewerExtensionRef": {
            "type": "object",
            "required": ["id", "component", "fileExtension"],
            "properties": {
                "id": {
                    "description": "Unique identifier for the navigation group",
                    "type": "string"
                },
                "component": {
                    "description": "Component id",
                    "type": "string"
                },
                "fileExtension": {
                    "description": "Target file extension",
                    "type": "string"
                },
                "order": {
                    "description": "Group order",
                    "type": "number"
                },
                "disabled": {
                    "description": "Toggles the disabled state",
                    "type": "boolean"
                }
            }
        }
    },

    "type": "object",
    "required": ["$name", "$version"],
    "properties": {
        "$name": {
            "description": "Extension name",
            "type": "string"
        },
        "$version": {
            "description": "Extension version",
            "type": "string"
        },
        "$description": {
            "description": "Brief description on what the extension does"
        },
        "$references": {
            "description": "References to external files",
            "type": "array",
            "items": {
                "type": "string"
            },
            "minItems": 1,
            "uniqueItems": true
        },
        "rules": {
            "description": "List of rule definitions",
            "type": "array",
            "items": { "$ref": "#/definitions/ruleRef" },
            "minItems": 1
        },
        "routes": {
            "description": "List of custom application routes",
            "type": "array",
            "items": { "$ref": "#/definitions/routeRef" },
            "minItems": 1
        },
        "actions": {
            "description": "List of action definitions",
            "type": "array",
            "items": { "$ref": "#/definitions/actionRef" },
            "minItems": 1
        },
        "features": {
            "description": "Application-specific features and extensions",
            "type": "object",
            "properties": {
                "create": {
                    "description": "The [New] menu component extensions",
                    "type": "array",
                    "items": { "$ref": "#/definitions/contentActionRef" },
                    "minItems": 1
                },
                "viewer": {
                    "description": "Viewer component extensions",
                    "type": "object",
                    "properties": {
                        "openWith": {
                            "description": "The [Open With] menu extensions",
                            "type": "array",
                            "items": { "$ref": "#/definitions/contentActionRef" },
                            "minItems": 1
                        },
                        "toolbar": {
                            "description": "Toolbar entries",
                            "type": "array",
                            "items": { "$ref": "#/definitions/contentActionRef" },
                            "minItems": 1
                        },
                        "content": {
                            "description": "Viewer content extensions",
                            "type": "array",
                            "items": { "$ref": "#/definitions/viewerExtensionRef" },
                            "minItems": 1
                        }
                    }
                },
                "navbar": {
                    "description": "Navigation bar extensions",
                    "type": "array",
                    "items": { "$ref": "#/definitions/navBarGroupRef" },
                    "minItems": 1
                },
                "sidebar": {
                    "description": "Sidebar extensions",
                    "type": "array",
                    "items": { "$ref": "#/definitions/sidebarTabRef" },
                    "minItems": 1
                },
                "toolbar": {
                    "description": "Toolbar entries",
                    "type": "array",
                    "items": { "$ref": "#/definitions/contentActionRef" },
                    "minItems": 1
                },
                "contextMenu": {
                    "description": "Context menu entries",
                    "type": "array",
                    "items": { "$ref": "#/definitions/contentActionRef" },
                    "minItems": 1
                }
            }
        }
    }
}

=== Alfresco/alfresco-content-app/projects/my-extension/assets/my-extension.json
{
    "$schema": "../../../extension.schema.json",
    "$version": "1.0.0",
    "$name": "plugin1",
    "$description": "demo plugin",

    "routes": [
        {
            "id": "my.extension.route",
            "path": "ext/my/route",
            "component": "my-extension.main.component"
        }
    ],

    "features": {
        "navbar": [
            {
                "id": "my.extension.nav",
                "items": [
                    {
                        "id": "my.extension.main",
                        "icon": "extension",
                        "title": "My Extension",
                        "route": "my.extension.route"
                    }
                ]
            }
        ]
    }
}

=== Alfresco/alfresco-content-app/src/assets/plugins/app.header.json
{
  "$schema": "../../../extension.schema.json",
  "$name": "app",
  "$version": "1.0.0",

  "actions": [
    {
      "id": "app.actions.about",
      "type": "NAVIGATE_URL",
      "payload": "/about"
    },
    {
      "id": "app.actions.settings",
      "type": "NAVIGATE_URL",
      "payload": "/settings"
    }
  ],

  "features": {
    "header": [
      {
        "id": "app.header.more",
        "type": "menu",
        "order": 10000,
        "icon": "more_vert",
        "title": "APP.ACTIONS.MORE",
        "children": [
          {
            "id": "app.header.settings",
            "title": "APP.SETTINGS.TITLE",
            "description": "APP.SETTINGS.TITLE",
            "icon": "settings",
            "actions": {
              "click": "app.actions.settings"
            }
          },
          {
            "id": "app.header.about",
            "title": "APP.BROWSE.ABOUT.TITLE",
            "description": "APP.BROWSE.ABOUT.TITLE",
            "icon": "info",
            "actions": {
              "click": "app.actions.about"
            }
          }
        ]
      }
    ]
  }
}

=== Alfresco/alfresco-content-app/src/assets/plugins/dev.tools.json
{
    "$schema": "../../../extension.schema.json",
    "$version": "1.0.0",
    "$name": "dev.tools",
    "$description": "ACA dev tools",

    "routes": [
        {
            "id": "app.dev.tools",
            "component": "app.dev.tools.component",
            "path": "dev-tools",
            "data": {
                "configPath": "assets/app.extensions.json",
                "pluginsPath": "assets/plugins",
                "schemaUri": "../../extension.schema.json",
                "schemaPath": "assets/extension.schema.json"
            }
        }
    ],

    "features": {
        "navbar": [
            {
                "id": "app.navbar.dev.tools",
                "items": [
                    {
                        "id": "app.navbar.dev.tools.main",
                        "icon": "build",
                        "title": "dev tools",
                        "route": "app.dev.tools"
                    }
                ]
            }
        ]
    }
}

=== Alfresco/alfresco-content-app/src/assets/plugins/metadata-plugin.json
{
  "$schema": "../../../extension.schema.json",
  "$version": "1.0.0",
  "$name": "metadata-plugin",
  "$description": "metadata card configuration plugin - testing purpose",
  "features": {
    "content-metadata": [
      {
        "id": "app.content.metadata.presets",
        "disabled": true
      },
      {
        "id": "app.content.metadata.presets2",
        "presets": {
          "custom": [
            {
              "title": "testing extension props",
              "items": [
                {
                  "aspect": "exif:exif",
                  "properties": [
                    "exif:pixelXDimension",
                    "exif:pixelYDimension",
                    "exif:dateTimeOriginal"
                  ]
                }
              ]
            }
          ]
        }
      }
    ]
  }
}
